VAR_GLOBAL
    awPyroRxtCh1Raw     : ARRAY[0..1] OF WORD;
    awPyroRxtCh2Raw     : ARRAY[0..1] OF WORD;
    awPyroRxtRatioRaw   : ARRAY[0..1] OF WORD;
    wPyroRxtAdcStatus   : WORD;
    wPyroRxtDevStatus   : WORD;

    awPyroSmartCh1Raw   : ARRAY[0..1] OF WORD;
    awPyroSmartCh2Raw   : ARRAY[0..1] OF WORD;
    awPyroSmartRatioRaw : ARRAY[0..1] OF WORD;
    wPyroSmartAdcStatus : WORD;
    wPyroSmartDevStatus : WORD;
END_VAR
